project:
  name: quickstart-new-relic-tdp
  owner: rkaul@newrelic.com
  package_lambda: false
  regions:
    - af-south-1
    - ap-east-1
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - eu-south-1
    - eu-north-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - me-south-1
    - sa-east-1
tests:
  nr-ec2-infra-agent-ssm-automation:
    parameters:
      NewRelicLicenseKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxNRAL'
      CreateEC2InstanceProfile: 'Yes'
    template: ./templates/NR-EC2InfraAgentSSMAutomation.template.yaml