// We need to work around Step numbers here if we are going to potentially exclude the AMI subscription
=== Sign in to your AWS account

. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For details, see link:#_planning_the_deployment[Planning the deployment] earlier in this guide.
. Make sure that your AWS account is configured correctly, as discussed in the link:#_technical_requirements[Technical requirements] section.

// Optional based on Marketplace listing. Not to be edited
ifdef::marketplace_subscription[]
=== Subscribe to the {partner-product-short-name} AMI

This Quick Start requires a subscription to the AMI for {partner-product-short-name} in AWS Marketplace.

. Sign in to your AWS account.
. {marketplace_listing_url}[Open the page for the {partner-product-short-name} AMI in AWS Marketplace], and then choose *Continue to Subscribe*.
. Review the terms and conditions for software usage, and then choose *Accept Terms*. +
  A confirmation page loads, and an email confirmation is sent to the account owner. For detailed subscription instructions, see the https://aws.amazon.com/marketplace/help/200799470[AWS Marketplace documentation^].

. When the subscription process is complete, exit out of AWS Marketplace without further action. *Do not* provision the software from AWS Marketplace—the Quick Start deploys the AMI for you.
endif::marketplace_subscription[]
// \Not to be edited

=== Launch the Quick Start
// Adapt the following warning to your Quick Start.
WARNING: If you’re deploying {partner-product-short-name} to monitor EC2 instances in private subnet without Internet access, you need to https://aws.amazon.com/premiumsupport/knowledge-center/ec2-systems-manager-vpc-endpoints/[enable Systems Manager access for private instances].

NOTE: You are responsible for the cost of the AWS services used while running this Quick Start reference deployment. There is no additional cost for using this Quick Start. For full details, see the pricing pages for each AWS service used by this Quick Start. Prices are subject to change.

This solution includes a CloudFormation template, viz. link:templates/NR-EC2InfraAgentSSMAutomation.yml[NR-EC2InfraAgentSSMAutomation.yml] that you deploy in your AWS account as StackSet. You should deploy the StackSet instances in your AWS accounts across all regions where you plan to have New Relic Infrastructure agent installed on your EC2 instances.
Each deployment takes about {deployment_time} to complete.

. Create a StackSet, viz. `NR-EC2InfraSSMAutomation` in your AWS account. It is recommended that you create it in your StackSet administration account or your Control Tower management account, but you can use any other account, if necessary. Use your https://docs.aws.amazon.com/IAM/latest/UserGuide/console_account-alias.html[AWS account ID] in place of `AWS_ACCOUNT_ID` placeholder. The template accepts your https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/new-relic-license-key[New Relic license key] as a parameter. Use it in place of `NEW_RELIC_LICENSE_KEY` placeholder. Use the actual IAM Role names for your StackSet administration and execution roles, for the placeholders, viz. `STACK_SET_ADMINISTRATION_ROLE_NAME` and `STACK_SET_EXECUTION_ROLE_NAME`, respectively.
+
----
aws cloudformation create-stack-set \
    --stack-set-name NR-EC2InfraSSMAutomation \
    --template-body file:./templates/NR-EC2InfraAgentSSMAutomation.yml \
    --description "SSM Automation workflow for installing New Relic Infrastructure Agent on EC2 instances" \
    --parameters ParameterKey=NewRelicLicenseKey,ParameterValue=<NEW_RELIC_LICENSE_KEY> \
    --capabilities CAPABILITY_NAMED_IAM \
    --administration-role-arn arn:aws:iam::<AWS_ACCOUNT_ID>:role/<STACK_SET_ADMINISTRATION_ROLE_NAME> \
    --execution-role-name <STACK_SET_EXECUTION_ROLE_NAME> \
    --permission-model SELF_MANAGED
----
+
After the command returns successfully, the StackSet creation starts. You can check the status of the StackSet creation after a few seconds. To verify the StackSet was successfully created, run the below command, and make sure the StackSet name, viz. `NR-EC2InfraSSMAutomation` is returned.
+
----
aws cloudformation describe-stack-set --stack-set-name NR-EC2InfraSSMAutomation --query "StackSet.StackSetName"
----

. Next, create instances of the `NR-EC2InfraSSMAutomation` StackSet across various AWS accounts and regions where you plan to launch EC2 instances. The following `create-stack-instances` example creates instances in two accounts and in four US regions.
+
----
aws cloudformation create-stack-instances \
    --stack-set-name NR-EC2InfraSSMAutomation \
    --accounts 123456789012 223456789012 \
    --regions us-east-1 us-east-2 us-west-1 us-west-2
----
+
After the command returns successfully, the Stack instances creation operation starts and an `OperationId` is returned. You can check the status of the operation after a few seconds. To verify the operation was successfully completed, run the below command, and make sure the status, viz. `SUCCEEDED` is returned. Use the returned `OperationId` value in place of `OPERATION_ID` placeholder.
+
----
aws cloudformation describe-stack-set-operation \
    --stack-set-name NR-EC2InfraSSMAutomation \
    --operation-id <OPERATION_ID> \
    --query "StackSetOperation.Status"
----
