// Replace the content in <>
// Briefly describe the software. Use consistent and clear branding. 
// Include the benefits of using the software on AWS, and provide details on usage scenarios.

= AWS QuickStart for New Relic EC2 Infrastructure integration

The Quick Start for New Relic EC2 Infrastructure integration comprises of an AWS CloudFormation template that you deploy to your AWS account(s) using StackSets. After you deploy the StackSet, it automatically triggers the automation workflow for the installation of New Relic Infrastructure agent in your EC2 instances based on a tag key-value pair match, as soon as the instances are launched. You can also run this automation workflow on-demand using AWS Management Console. +
The QuickStart relies on https://aws.amazon.com/systems-manager/[AWS Systems Manager] (SSM) https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-automation.html[Automation] and requires that EC2 instances have the https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent.html[SSM Agent] installed.
